service: troep
configValidationMode: error

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: eu-west-3
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: production
    runtime: provided.al2
    lambdaHashingVersion: 20201221
    apiGateway:
        binaryMediaTypes:
            - '*/*'
    environment:
        BREF_BINARY_RESPONSES: '1'

package:
    patterns:
        # Directories to exclude from deployment
        - '!node_modules/**'
        - '!database/**'
        - '!tests/**'

functions:
    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            -   httpApi: '*'
    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-74} # PHP
            - ${bref:layer.console} # The "console" layer

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
